version: '3.3'

services:
  builder: &go-base
    image: golang:latest
    volumes:
      - ./mod_cache:/go/pkg/mod
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: 'go build -v -o main ./app/cmd/main'
  linter:
    <<: *go-base
    image: golangci/golangci-lint:latest
    command: 'golangci-lint run'
  unit-tester:
    <<: *go-base
    command: > 
      go test -v 
      ./app/cmd