version: '3.8'

services:
  builder: &go-base
    image: golang:latest
    volumes:
      - ./mod_cache:/go/pkg/mod
      - .:/usr/src/app
    working_dir: /usr/src/app
    command: 'go build -o ./app/cmd/main'
  linter:
    <<: *go-base
    image: golangci/golangci-lint:latest
    command: 'golangci-lint run'
  unit-tester:
    <<: *go-base
    command: > 
      go test -v 
      ./app/cmd
  integration-tester:
    <<: *go-base
    command: >
      go test -v
      ./app/repositories
    depends_on:
      - db
  db:
    container_name: testdb
    image: postgres:latest
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=12345
      - POSTGRES_DB=avitobd
    volumes:
      - postgres-db:/var/lib/postgresql/data
      - ./app/database/sql/00_create_database.sql:/docker-entrypoint-initdb.d/00_create_database.sql

volumes:
  postgres-db:
