version: '3.3'

services:
  linter:
    image: golangci/golangci-lint:latest
    volumes:
      - ./mod_cache:/go/pkg/mod
      - ./app/cmd:/usr/src/app
    working_dir: /usr/src/app
    command: 'golangci-lint run'

  tester:
    image: golang:latest
    volumes:
      - ./mod_cache:/go/pkg/mod
      - ./app/cmd:/usr/src/app
    working_dir: /usr/src/app
    command: 'go test -v ./...'