name: Test

on:
  push:
    branches:
      - "develop"
      - "feature/**"
      - "fix/**"
      - "master"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Lint
      uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: './docker-compose.ci.yml'
        service: linter

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run Unit Tests
      uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: './docker-compose.ci.yml'
        service: unit-tester

    - name: Run Integration Tests
      uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: './docker-compose.ci.yml'
        service: integration-tester

  build:
    runs-on: ubuntu-latest
    environment: test
    steps:
    - name: Create .env file
      run: | 
        echo "${{ secrets.ENV_FILE }}" > ./.env

    - uses: actions/checkout@v3

    - name: Build
      uses: adrielcodeco/docker-compose-run-action@v1
      with:
        compose-file: './docker-compose.ci.yml'
        service: builder
    
    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: main
        path: ./app/cmd/main